version: '3'
services:
  robocat:
    env_file: .env
    restart: always
    build:
        context: .
    ports:
    #   - ${WEB_PORT:-80}:80
    #   - ${VNC_PORT:-5900}:5900
        - 80
        - 5900
    volumes:
      - ./flow:/home/robocat/flow
